# Generated by Django 5.0.4 on 2024-04-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('max_votes', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nr_pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.election')),
            ],
        ),
        migrations.CreateModel(
            name='Election_Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.election')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.user'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.election')),
            ],
        ),
        migrations.CreateModel(
            name='Voted_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votingapp.user')),
            ],
        ),
    ]
